const sampleListings = [
  // ===== STAYS - Houses =====
  {
    title: "Modern Luxury Villa with Pool",
    description: "Stunning modern villa with infinity pool, panoramic mountain views, and contemporary architecture.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1661883964999-c1bcb57a7357?q=80&w=1128&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aG91c2VzfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1689609950112-d66095626efb?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
      { filename: "gallery3", url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG91c2V8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 4500,
    location: "Goa",
    country: "India",
    parentCategory: "stays",
    category: "houses",
    pricingUnit: "night",
    maxGuests: 6,
    geometry: { type: "Point", coordinates: [73.7319, 15.2993] },
    categoryFields: {
      bedrooms: 3,
      bathrooms: 2,
      beds: 4,
      amenities: ["wifi", "ac", "kitchen", "parking", "beachAccess"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 14,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Contemporary Urban Home",
    description: "Modern architectural masterpiece with clean lines, open spaces, and natural light throughout.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8aG91c2V8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzR8fGhvdXNlfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1487975460695-a2e5c4ea12c9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjU4fHxob3VzZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 3200,
    location: "Mumbai",
    country: "India",
    parentCategory: "stays",
    category: "houses",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      bedrooms: 1,
      bathrooms: 1,
      floor: 12,
      amenities: ["wifi", "ac", "gym", "elevator", "security"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 30,
      checkInTime: "15:00",
      checkOutTime: "11:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Minimalist Retreat Home",
    description: "Clean, minimalist design with focus on simplicity and tranquility in natural surroundings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1697462248415-0ead58a3daba?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDE0fHxob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1553968827-4a768f5bb872?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTMzfHxob3VzZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2800,
    location: "Jaipur",
    country: "India",
    parentCategory: "stays",
    category: "houses",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
    categoryFields: {
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["wifi", "ac", "breakfast"],
      sharedSpaces: ["courtyard", "rooftop", "dining"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== STAYS - Villas =====
  {
    title: "Mediterranean Luxury Villa",
    description: "Beautiful Mediterranean-style villa with private pool, gardens, and traditional architecture.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1682377521753-58d1fd9fa5ce?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dmlsbGFzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmlsbGFzfGVufDB8fDB8fHww" },
    ],
    price: 12000,
    location: "Lonavala",
    country: "India",
    parentCategory: "stays",
    category: "villas",
    pricingUnit: "night",
    maxGuests: 10,
    geometry: { type: "Point", coordinates: [73.4073, 18.7546] },
    categoryFields: {
      bedrooms: 4,
      bathrooms: 4,
      beds: 6,
      pool: true,
      amenities: ["wifi", "ac", "kitchen", "parking", "pool", "bbq", "garden"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 7,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 72,
      instantBook: false,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Lakeside Modern Villa",
    description: "Contemporary villa located by a tranquil lake with floor-to-ceiling windows and modern amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dmlsbGFzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1723110994499-df46435aa4b3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8dmlsbGFzfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1661915661139-5b6a4e4a6fcc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8dmlsbGFzfGVufDB8fDB8fHww" },
    ],
    price: 18000,
    location: "Alibaug",
    country: "India",
    parentCategory: "stays",
    category: "villas",
    pricingUnit: "night",
    maxGuests: 8,
    geometry: { type: "Point", coordinates: [72.8682, 18.6414] },
    categoryFields: {
      bedrooms: 4,
      bathrooms: 3,
      beds: 5,
      pool: true,
      amenities: ["wifi", "ac", "kitchen", "parking", "pool", "beachAccess", "staff"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 10,
      checkInTime: "15:00",
      checkOutTime: "11:00",
      advanceNotice: 48,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Tropical Paradise Villa",
    description: "Villa surrounded by lush tropical gardens with open-air living spaces and exotic ambiance.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHZpbGxhc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHZpbGxhc3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1682377521697-bc598b52b08a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHZpbGxhc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 15000,
    location: "Kerala",
    country: "India",
    parentCategory: "stays",
    category: "villas",
    pricingUnit: "night",
    maxGuests: 6,
    geometry: { type: "Point", coordinates: [76.2711, 10.8505] },
    categoryFields: {
      bedrooms: 3,
      bathrooms: 3,
      beds: 4,
      pool: true,
      amenities: ["wifi", "ac", "kitchen", "parking", "pool", "garden", "staff"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 14,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== STAYS - Farm Stays =====
  {
    title: "Traditional Farmhouse",
    description: "Classic country farmhouse with rustic charm, vegetable gardens, and peaceful rural setting.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1663088800901-c57258d8707a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1601189992152-6ef7ebb531a8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1592212671488-700bb9a101e1?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww" },
    ],
    price: 3500,
    location: "Coorg",
    country: "India",
    parentCategory: "stays",
    category: "farm-stays",
    pricingUnit: "night",
    maxGuests: 6,
    geometry: { type: "Point", coordinates: [75.7382, 12.3375] },
    categoryFields: {
      bedrooms: 2,
      bathrooms: 2,
      farmActivities: ["milking", "harvesting", "cooking", "trekking"],
      amenities: ["wifi", "meals", "parking", "bonfire"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 7,
      checkInTime: "12:00",
      checkOutTime: "10:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Rustic Barn Conversion",
    description: "Beautifully converted barn with original features, exposed beams, and modern comforts.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1685133855379-711aa008f7ba?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1489657780376-e0d8630c4bd3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1603951743220-867ee4ae77d4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww" },
    ],
    price: 4200,
    location: "Himachal",
    country: "India",
    parentCategory: "stays",
    category: "farm-stays",
    pricingUnit: "night",
    maxGuests: 8,
    geometry: { type: "Point", coordinates: [76.2711, 31.1048] },
    categoryFields: {
      bedrooms: 3,
      bathrooms: 2,
      farmActivities: ["animal feeding", "organic farming", "cheese making"],
      amenities: ["wifi", "fireplace", "parking", "bbq"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 10,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Mountain Farm Cottage",
    description: "Charming cottage on a working mountain farm with spectacular valley views.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1733760180239-ef05b25dd5ad?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZmFybSUyMGhvdXNlfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1534073133331-c4b62a557083?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGZhcm0lMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 3800,
    location: "Darjeeling",
    country: "India",
    parentCategory: "stays",
    category: "farm-stays",
    pricingUnit: "night",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [88.2627, 27.036] },
    categoryFields: {
      bedrooms: 2,
      bathrooms: 1,
      farmActivities: ["tea picking", "gardening", "bird watching"],
      amenities: ["wifi", "fireplace", "parking", "organic meals"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "14:00",
      checkOutTime: "10:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== STAYS - Treehouses =====
  {
    title: "Modern Eco Treehouse",
    description: "Sustainable treehouse with modern design, built around living trees in a forest canopy.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1664047696174-72d3d84e6d5e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJlZWhvdXNlfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1550934482-7904d33d1b54?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJlZWhvdXNlfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1618767689160-da3fb810aad7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dHJlZWhvdXNlfGVufDB8fDB8fHww" },
    ],
    price: 5500,
    location: "Wayanad",
    country: "India",
    parentCategory: "stays",
    category: "treehouses",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [76.0849, 11.6854] },
    categoryFields: {
      bedrooms: 1,
      height: "30 feet",
      accessibility: "ladder",
      amenities: ["electricity", "attached-bath", "balcony"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 3,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Forest Canopy Retreat",
    description: "Treehouse nestled high in the forest canopy with panoramic views and peaceful surroundings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1604004218771-05c55db4f9f4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dHJlZWhvdXNlfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1550355191-aa8a80b41353?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dHJlZWhvdXNlfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1547393429-098dd122091a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHRyZWVob3VzZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 4800,
    location: "Assam",
    country: "India",
    parentCategory: "stays",
    category: "treehouses",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [91.7432, 26.1445] },
    categoryFields: {
      bedrooms: 1,
      height: "25 feet",
      accessibility: "stairs",
      amenities: ["electricity", "bathroom", "balcony", "hammock"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 5,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Luxury Treetop Suite",
    description: "High-end treehouse with luxury amenities, glass walls, and breathtaking forest views.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1685305676839-26406ddbe4de?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHRyZWVob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1683129807206-8a648874655e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRyZWVob3VzZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 6500,
    location: "Karnataka",
    country: "India",
    parentCategory: "stays",
    category: "treehouses",
    pricingUnit: "night",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [75.7139, 15.3173] },
    categoryFields: {
      bedrooms: 2,
      height: "35 feet",
      accessibility: "bridge",
      amenities: ["electricity", "hot water", "kitchenette", "private deck"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 7,
      checkInTime: "15:00",
      checkOutTime: "11:00",
      advanceNotice: 72,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },

  // ===== STAYS - Camping =====
  {
    title: "Lakeside Camping Experience",
    description: "Peaceful camping by a serene lake with comfortable tents and beautiful sunrise views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1661916911093-b2e5f005938f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2500,
    location: "Manali",
    country: "India",
    parentCategory: "stays",
    category: "camping",
    pricingUnit: "night",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
    categoryFields: {
      tentProvided: true,
      campfireAllowed: true,
      facilities: ["meals", "bonfire", "trekking-guide", "sleeping-bags"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 5,
      checkInTime: "13:00",
      checkOutTime: "10:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Mountain Base Camp",
    description: "Comfortable base camp setup at the foothills of majestic mountains, perfect for trekkers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1631635589499-afd87d52bf64?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1576176539998-0237d1ac6a85?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1532339142463-fd0a8979791a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 3000,
    location: "Uttarakhand",
    country: "India",
    parentCategory: "stays",
    category: "camping",
    pricingUnit: "night",
    maxGuests: 6,
    geometry: { type: "Point", coordinates: [79.0193, 30.0668] },
    categoryFields: {
      tentProvided: true,
      campfireAllowed: true,
      facilities: ["meals", "guide", "equipment rental", "medical assistance"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 10,
      checkInTime: "12:00",
      checkOutTime: "10:00",
      advanceNotice: 72,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Desert Camp Experience",
    description: "Authentic desert camping with traditional tents under the starlit sky.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1537905569824-f89f14cceb68?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 2800,
    location: "Rajasthan",
    country: "India",
    parentCategory: "stays",
    category: "camping",
    pricingUnit: "night",
    maxGuests: 8,
    geometry: { type: "Point", coordinates: [70.9027, 26.9124] },
    categoryFields: {
      tentProvided: true,
      campfireAllowed: true,
      facilities: ["meals", "cultural shows", "camel rides", "bathroom facilities"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 3,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== STAYS - Private Rooms =====
  {
    title: "Designer Studio Room",
    description: "Modern designer room with artistic touches and premium furnishings in a central location.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1673014202228-65e0e9064a34?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8cHJpdmF0ZSUyMHJvb218ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1758632031161-b6d7e913c2b9?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHByaXZhdGUlMjByb29tfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1697124510306-26d01f1b775f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHByaXZhdGUlMjByb29tfGVufDB8fDB8fHww" },
    ],
    price: 1800,
    location: "Bangalore",
    country: "India",
    parentCategory: "stays",
    category: "private-rooms",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["wifi", "ac", "workspace", "ensuite"],
      sharedSpaces: ["kitchen", "living room", "terrace"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 30,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Minimalist Private Suite",
    description: "Clean, minimalist private suite with high-end finishes and thoughtful design details.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1761682719858-5046d0cbbaae?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHByaXZhdGUlMjByb29tfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1661923743277-2086a56bc664?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHByaXZhdGUlMjByb29tfGVufDB8fDB8fHww" },
    ],
    price: 2200,
    location: "Pune",
    country: "India",
    parentCategory: "stays",
    category: "private-rooms",
    pricingUnit: "night",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
    categoryFields: {
      bedrooms: 1,
      bathrooms: 1,
      amenities: ["wifi", "ac", "smart tv", "mini-fridge"],
      sharedSpaces: ["garden", "swimming pool"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "15:00",
      checkOutTime: "11:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== VEHICLES - Cars =====
  {
    title: "Luxury Sports Car",
    description: "High-performance sports car with premium features for an exhilarating driving experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2500,
    location: "Bangalore",
    country: "India",
    parentCategory: "vehicles",
    category: "cars",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      make: "Toyota",
      model: "Innova Crysta",
      year: 2022,
      fuelType: "diesel",
      transmission: "automatic",
      seats: 7,
      mileageLimit: "300 km/day",
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 30,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Premium SUV for Family",
    description: "Spacious and comfortable SUV perfect for family trips with all modern amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNhcnN8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 3500,
    location: "Leh",
    country: "India",
    parentCategory: "vehicles",
    category: "cars",
    pricingUnit: "day",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [77.5771, 34.1526] },
    categoryFields: {
      make: "Mahindra",
      model: "Thar",
      year: 2023,
      fuelType: "diesel",
      transmission: "manual",
      seats: 4,
      mileageLimit: "unlimited",
    },
    bookingSettings: {
      minStay: 3,
      maxStay: 14,
      checkInTime: "07:00",
      checkOutTime: "19:00",
      advanceNotice: 48,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Classic Vintage Car",
    description: "Beautifully restored classic car for special occasions and memorable drives.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNhcnN8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1555353540-64580b51c258?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGNhcnN8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 5000,
    location: "Goa",
    country: "India",
    parentCategory: "vehicles",
    category: "cars",
    pricingUnit: "day",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [73.7319, 15.2993] },
    categoryFields: {
      make: "Classic",
      model: "Vintage",
      year: 1970,
      fuelType: "petrol",
      transmission: "manual",
      seats: 4,
      mileageLimit: "100 km/day",
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 3,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 72,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },

  // ===== VEHICLES - Bikes =====
  {
    title: "Adventure Touring Bike",
    description: "Perfect adventure bike for long-distance touring and mountain roads.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1661963826911-f369fa24c1a6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmlrZXN8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1610553556003-9b2ae8ef1b8e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmlrZXN8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmlrZXN8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 1500,
    location: "Manali",
    country: "India",
    parentCategory: "vehicles",
    category: "bikes",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
    categoryFields: {
      make: "Royal Enfield",
      model: "Himalayan",
      engineCC: 411,
      fuelType: "petrol",
      helmetIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 21,
      checkInTime: "08:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Modern Street Bike",
    description: "Sleek and powerful street bike perfect for urban commuting and weekend rides.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1641851544195-c3629b9cde93?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJpa2VzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGJpa2VzfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1566891439633-e4c86e294493b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGJpa2VzfGVufDB8fDB8fHww" },
    ],
    price: 1200,
    location: "Delhi",
    country: "India",
    parentCategory: "vehicles",
    category: "bikes",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      make: "KTM",
      model: "Duke 390",
      engineCC: 390,
      fuelType: "petrol",
      helmetIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "09:00",
      checkOutTime: "19:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== VEHICLES - Scooters =====
  {
    title: "Modern Electric Scooter",
    description: "Eco-friendly electric scooter perfect for city commuting with zero emissions.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1554223789-df81106a45ed?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2Nvb3RlcnxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1503434396599-58ba8a18d932?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2Nvb3RlcnxlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1519750292352-c9fc17322ed7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2Nvb3RlcnxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 400,
    location: "Goa",
    country: "India",
    parentCategory: "vehicles",
    category: "scooters",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [73.7319, 15.2993] },
    categoryFields: {
      make: "Honda",
      model: "Activa 6G",
      electric: false,
      range: "180 km",
      helmetIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 30,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Vintage Style Scooter",
    description: "Classic style scooter with modern features, perfect for stylish city rides.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1538895490524-0ded232a96d8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNjb290ZXJ8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1478340168842-7e6b25ed6510?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHNjb290ZXJ8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1623079478319-945f25f0a97b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNjb290ZXJ8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 350,
    location: "Mumbai",
    country: "India",
    parentCategory: "vehicles",
    category: "scooters",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      make: "Vespa",
      model: "Classic",
      electric: false,
      range: "150 km",
      helmetIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "20:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== VEHICLES - EVs =====
  {
    title: "Luxury Electric Car",
    description: "Premium electric vehicle with long range and luxury features for comfortable travel.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1715639312136-56a01f236440?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZXZzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1715789261470-fb25ffbf70d3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWxlY3RyaWMlMjB2ZWhpY2xlc3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1617886322168-72b886573c35?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZWxlY3RyaWMlMjB2ZWhpY2xlc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2800,
    location: "Pune",
    country: "India",
    parentCategory: "vehicles",
    category: "evs",
    pricingUnit: "day",
    maxGuests: 5,
    geometry: { type: "Point", coordinates: [73.8567, 18.5204] },
    categoryFields: {
      make: "Tata",
      model: "Nexon EV",
      range: "300 km",
      chargingType: "Type 2",
      seats: 5,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: true,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Compact Electric Vehicle",
    description: "Small and efficient electric car perfect for city driving and easy parking.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1615383690110-62acb993993e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGVsZWN0cmljJTIwdmVoaWNsZXN8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1666919643134-d97687c1826c?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZWxlY3RyaWMlMjB2ZWhpY2xlc3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1715702638527-1a7f52e8cc6f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZWxlY3RyaWMlMjB2ZWhpY2xlc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2200,
    location: "Bangalore",
    country: "India",
    parentCategory: "vehicles",
    category: "evs",
    pricingUnit: "day",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      make: "MG",
      model: "ZS EV",
      range: "350 km",
      chargingType: "CCS",
      seats: 4,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== VEHICLES - Bicycles =====
  {
    title: "Premium Road Bike",
    description: "High-performance road bike for serious cyclists and long-distance rides.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1678718713393-2b88cde9605b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmljeWNsZXxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmljeWNsZXxlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmljeWNsZXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 600,
    location: "Shimla",
    country: "India",
    parentCategory: "vehicles",
    category: "bicycles",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
    categoryFields: {
      type: "mountain",
      gears: 21,
      helmetIncluded: true,
      lockIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "07:00",
      checkOutTime: "19:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Modern City Bicycle",
    description: "Comfortable city bike perfect for urban exploration and daily commuting.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618762044398-ec1e7e048bbd?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmljeWNsZXxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1505705694340-019e1e335916?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmljeWNsZXxlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJpY3ljbGV8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 400,
    location: "Delhi",
    country: "India",
    parentCategory: "vehicles",
    category: "bicycles",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      type: "city",
      gears: 7,
      helmetIncluded: true,
      lockIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Vintage Style Bicycle",
    description: "Classic retro-style bicycle with modern components for a stylish ride.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523740856324-f2ce89135981?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJpY3ljbGV8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [],
    price: 350,
    location: "Jaipur",
    country: "India",
    parentCategory: "vehicles",
    category: "bicycles",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
    categoryFields: {
      type: "vintage",
      gears: 3,
      helmetIncluded: true,
      lockIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "19:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== EQUIPMENT - Cameras =====
  {
    title: "Professional Mirrorless Camera",
    description: "State-of-the-art mirrorless camera with full-frame sensor and professional features.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1663134149019-284682ece04c?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2FtYXJhfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FtYXJhfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtYXJhfGVufDB8fDB8fHww" },
    ],
    price: 2000,
    location: "Mumbai",
    country: "India",
    parentCategory: "equipment",
    category: "cameras",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      brand: "Sony",
      model: "A7 III",
      type: "mirrorless",
      megapixels: 24.2,
      accessories: ["24-70mm lens", "2x batteries", "64GB SD card", "camera bag"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Vintage Film Camera",
    description: "Classic film camera with manual controls for authentic photography experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1580707221190-bd94d9087b7f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2FtYXJhfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1516961642265-531546e84af2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y2FtYXJhfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1616088886430-ccd86fef0713?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNhbWFyYXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 1500,
    location: "Delhi",
    country: "India",
    parentCategory: "equipment",
    category: "cameras",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      brand: "Leica",
      model: "M6",
      type: "film",
      filmFormat: "35mm",
      accessories: ["50mm lens", "light meter", "film rolls", "case"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "10:00",
      checkOutTime: "18:00",
      advanceNotice: 48,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Professional DSLR Kit",
    description: "Complete professional DSLR setup with multiple lenses and accessories.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1460134846237-51c777df6111?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGNhbWFyYXxlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1603208234872-619ffa1209cb?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGNhbWFyYXxlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 2500,
    location: "Bangalore",
    country: "India",
    parentCategory: "equipment",
    category: "cameras",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      brand: "Canon",
      model: "5D Mark IV",
      type: "DSLR",
      megapixels: 30.4,
      accessories: ["24-105mm lens", "70-200mm lens", "tripod", "flash"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },

  // ===== EQUIPMENT - Drones =====
  {
    title: "Professional 4K Drone",
    description: "High-end drone with 4K camera for professional aerial photography and videography.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1714618849685-89cad85746b1?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZHJvbmV8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHJvbmV8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZHJvbmV8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 3500,
    location: "Delhi",
    country: "India",
    parentCategory: "equipment",
    category: "drones",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      brand: "DJI",
      model: "Mavic 3 Pro",
      flightTime: "40 min",
      cameraQuality: "5.1K",
      accessories: ["3x batteries", "ND filters", "carrying case", "spare propellers"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 48,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Compact Travel Drone",
    description: "Small, foldable drone perfect for travel and on-the-go aerial photography.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGRyb25lfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1495764506633-93d4dfed7c6b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGRyb25lfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1532989029401-439615f3d4b4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGRyb25lfGVufDB8fDB8fHww" },
    ],
    price: 2200,
    location: "Goa",
    country: "India",
    parentCategory: "equipment",
    category: "drones",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [73.7319, 15.2993] },
    categoryFields: {
      brand: "DJI",
      model: "Mini 3 Pro",
      flightTime: "34 min",
      cameraQuality: "4K",
      accessories: ["2x batteries", "charging hub", "carrying case"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== EQUIPMENT - Lighting =====
  {
    title: "Professional Studio Lighting",
    description: "Complete studio lighting setup for professional photography and videography.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1553095066-5014bc7b7f2d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1606175063459-796dce40e3aa?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1678052582163-c7b25ccde9e6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 1500,
    location: "Hyderabad",
    country: "India",
    parentCategory: "equipment",
    category: "lighting",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [78.4867, 17.385] },
    categoryFields: {
      type: "studio strobes",
      watts: 600,
      accessories: ["3x softboxes", "3x light stands", "wireless trigger", "carrying cases"],
      quantity: 3,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "LED Video Lighting Kit",
    description: "Professional LED lighting setup for video production and streaming.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1532182772104-90f63a50fec5?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1561794919-75618574e915?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1515948725-edac7b5bb0fc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bGlnaHRpbmd8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 1200,
    location: "Mumbai",
    country: "India",
    parentCategory: "equipment",
    category: "lighting",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      type: "LED panels",
      colorTemp: "5600K",
      accessories: ["light stands", "diffusers", "batteries", "carrying case"],
      quantity: 3,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 14,
      checkInTime: "10:00",
      checkOutTime: "19:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Portable Lighting Setup",
    description: "Compact and portable lighting kit for location shoots and events.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523376460408-aeb5f5d051b8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxpZ2h0aW5nfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1563099045-dd7d9aebaa49?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGxpZ2h0aW5nfGVufDB8fDB8fHww" },
    ],
    price: 800,
    location: "Chennai",
    country: "India",
    parentCategory: "equipment",
    category: "lighting",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [80.2707, 13.0827] },
    categoryFields: {
      type: "continuous lighting",
      power: "battery operated",
      accessories: ["stands", "diffusers", "battery packs", "case"],
      quantity: 2,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== ADVENTURE - Tents =====
  {
    title: "Premium Camping Tent",
    description: "High-quality camping tent for comfortable outdoor adventures in all seasons.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1669047983409-5879cfb7831a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGVudHN8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1605289609008-188320c69892?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGVudHN8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1624923686627-514dd5e57bae?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dGVudHN8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 800,
    location: "Rishikesh",
    country: "India",
    parentCategory: "adventure",
    category: "tents",
    pricingUnit: "day",
    maxGuests: 4,
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
    categoryFields: {
      capacity: 4,
      type: "dome",
      seasonRating: "4-season",
      weight: "3.5 kg",
      accessories: ["rain fly", "footprint", "stakes", "repair kit"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 14,
      checkInTime: "08:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Family Camping Tent",
    description: "Spacious tent perfect for family camping trips with multiple rooms.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1603738397297-a374b78e9626?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dGVudHN8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1681169152396-f22381eae362?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dGVudHN8ZW58MHx8MHx8fDA%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1606814399166-22faa3453007?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGVudHN8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 1000,
    location: "Manali",
    country: "India",
    parentCategory: "adventure",
    category: "tents",
    pricingUnit: "day",
    maxGuests: 6,
    geometry: { type: "Point", coordinates: [77.1887, 32.2396] },
    categoryFields: {
      capacity: 6,
      type: "cabin",
      seasonRating: "3-season",
      weight: "5.2 kg",
      accessories: ["room divider", "gear loft", "rain fly", "stakes"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "10:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Ultralight Backpacking Tent",
    description: "Lightweight tent designed for backpackers and minimalist camping.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1731082627921-77d00a9e5ab7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRlbnRzfGVufDB8fDB8fHww",
    },
    gallery: [],
    price: 600,
    location: "Himachal",
    country: "India",
    parentCategory: "adventure",
    category: "tents",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
    categoryFields: {
      capacity: 2,
      type: "dome",
      seasonRating: "3-season",
      weight: "1.8 kg",
      accessories: ["rain fly", "stakes", "stuff sack"],
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 21,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== ADVENTURE - Trekking =====
  {
    title: "Complete Trekking Gear Package",
    description: "All essential trekking equipment for a comfortable and safe mountain adventure.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1677002240252-af3f88114efc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJla2luZ3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJla2luZ3xlbnwwfHwwfHx8MA%3D%3D" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1606175063459-796dce40e3aa?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dHJla2luZ3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 500,
    location: "Darjeeling",
    country: "India",
    parentCategory: "adventure",
    category: "trekking",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [88.2627, 27.036] },
    categoryFields: {
      type: "complete kit",
      size: "60L backpack",
      brand: "Wildcraft",
      condition: "excellent",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 21,
      checkInTime: "08:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Mountain Expedition Gear",
    description: "Professional grade equipment for high-altitude trekking and expeditions.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1663036844449-bbf050cfda75?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHRyZWtpbmd8ZW58MHx8MHx8fDA%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1647975648581-823fb7d19712?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHRyZWtpbmd8ZW58MHx8MHx8fDA%3D" },
    ],
    price: 750,
    location: "Ladakh",
    country: "India",
    parentCategory: "adventure",
    category: "trekking",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.5771, 34.1526] },
    categoryFields: {
      type: "expedition gear",
      size: "70L backpack",
      brand: "The North Face",
      condition: "excellent",
    },
    bookingSettings: {
      minStay: 3,
      maxStay: 30,
      checkInTime: "08:00",
      checkOutTime: "18:00",
      advanceNotice: 48,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Hiking Essentials Kit",
    description: "Basic hiking gear for day trips and light trekking adventures.",
    image: {
      filename: "listingimage",
      url: "https://media.istockphoto.com/id/483629308/photo/silhouettes-of-hikers-at-sunset.webp?a=1&b=1&s=612x612&w=0&k=20&c=ZSYhE3Ojkht8fW9s2gyVvvt19DmOtGfjQAI2v_GosGU=",
    },
    gallery: [],
    price: 300,
    location: "Munnar",
    country: "India",
    parentCategory: "adventure",
    category: "trekking",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.0591, 10.0889] },
    categoryFields: {
      type: "day hike kit",
      size: "30L backpack",
      brand: "Decathlon",
      condition: "good",
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "09:00",
      checkOutTime: "18:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== ADVENTURE - Kayaks =====
  {
    title: "Tandem Kayak for Two",
    description: "Stable tandem kayak perfect for couples or friends exploring lakes and calm waters.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1661893427047-16f6ddc173f6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8S2F5YWtzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1562388831-a7a060b9c1fe?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8S2F5YWtzfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1588472235276-7638965471e2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8S2F5YWtzfGVufDB8fDB8fHww" },
    ],
    price: 1200,
    location: "Goa",
    country: "India",
    parentCategory: "adventure",
    category: "kayaks",
    pricingUnit: "day",
    maxGuests: 2,
    geometry: { type: "Point", coordinates: [73.7319, 15.2993] },
    categoryFields: {
      type: "sit-on-top",
      capacity: 2,
      length: "14 feet",
      paddleIncluded: true,
      vestIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "07:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Single Touring Kayak",
    description: "Efficient touring kayak designed for longer journeys and sea kayaking.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1668866451605-b067bd3c9569?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8S2F5YWtzfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1627625591762-3cf527919054?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8S2F5YWtzfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1719258264857-9c380d840a1a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fEtheWFrc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 900,
    location: "Kerala",
    country: "India",
    parentCategory: "adventure",
    category: "kayaks",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [76.2711, 10.8505] },
    categoryFields: {
      type: "sit-inside",
      capacity: 1,
      length: "16 feet",
      paddleIncluded: true,
      vestIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 5,
      checkInTime: "08:00",
      checkOutTime: "18:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Recreational Kayak",
    description: "Stable and easy-to-use kayak perfect for beginners and recreational paddling.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1661810923761-c2e55f5b555d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fEtheWFrc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [],
    price: 700,
    location: "Andaman",
    country: "India",
    parentCategory: "adventure",
    category: "kayaks",
    pricingUnit: "day",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [92.6586, 11.6234] },
    categoryFields: {
      type: "sit-on-top",
      capacity: 1,
      length: "10 feet",
      paddleIncluded: true,
      vestIncluded: true,
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 7,
      checkInTime: "08:00",
      checkOutTime: "17:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== PROFESSIONAL - Coworking =====
  {
    title: "Premium Coworking Space",
    description: "Modern coworking space with dedicated desks, meeting rooms, and premium amenities.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1684769161054-2fa9a998dcb6?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Q293b3JraW5nfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q293b3JraW5nfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1523908511403-7fc7b25592f4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q293b3JraW5nfGVufDB8fDB8fHww" },
    ],
    price: 150,
    location: "Bangalore",
    country: "India",
    parentCategory: "professional",
    category: "coworking",
    pricingUnit: "hour",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      desks: 1,
      wifi: "100 Mbps",
      amenities: ["printer", "coffee", "lockers", "phone booths"],
      meetingRooms: "2 hours/day included",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 12,
      checkInTime: "08:00",
      checkOutTime: "22:00",
      advanceNotice: 2,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Creative Coworking Studio",
    description: "Artistic coworking space designed for creatives with inspiring decor and collaborative areas.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q293b3JraW5nfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1668383209648-029c09c32811?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Q293b3JraW5nfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1522071901873-411886a10004?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fENvd29ya2luZ3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 120,
    location: "Mumbai",
    country: "India",
    parentCategory: "professional",
    category: "coworking",
    pricingUnit: "hour",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      desks: 1,
      wifi: "200 Mbps",
      amenities: ["printing", "coffee", "lounge", "event space"],
      meetingRooms: "1 hour/day included",
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 8,
      checkInTime: "08:00",
      checkOutTime: "22:00",
      advanceNotice: 2,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Executive Coworking Lounge",
    description: "Premium business lounge with private booths and professional atmosphere.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1604328703693-18313fe20f3a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fENvd29ya2luZ3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fENvd29ya2luZ3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 180,
    location: "Delhi",
    country: "India",
    parentCategory: "professional",
    category: "coworking",
    pricingUnit: "hour",
    maxGuests: 1,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      desks: 1,
      wifi: "500 Mbps",
      amenities: ["private booths", "concierge", "business center", "catering"],
      meetingRooms: "unlimited access",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 10,
      checkInTime: "07:00",
      checkOutTime: "23:00",
      advanceNotice: 4,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },

  // ===== PROFESSIONAL - Meeting Rooms =====
  {
    title: "Executive Boardroom",
    description: "Luxurious boardroom with premium furnishings and advanced technology for important meetings.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1661497336283-c4176da1078e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bWVldGluZyUyMHJvb21zfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWVldGluZyUyMHJvb21zfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1661931749081-23d69ddb62d1?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bWVldGluZyUyMHJvb21zfGVufDB8fDB8fHww" },
    ],
    price: 500,
    location: "Mumbai",
    country: "India",
    parentCategory: "professional",
    category: "meeting-rooms",
    pricingUnit: "hour",
    maxGuests: 12,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      capacity: 12,
      projector: true,
      whiteboard: true,
      videoConf: "Zoom/Teams ready",
      amenities: ["ac", "water", "tea/coffee", "stationery"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 8,
      checkInTime: "08:00",
      checkOutTime: "20:00",
      advanceNotice: 12,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },
  {
    title: "Modern Conference Room",
    description: "Contemporary meeting space with smart technology and comfortable seating.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1744095407215-66e40734e23a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fG1lZXRpbmclMjByb29tc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1677078610072-7f11ebc4d4d7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG1lZXRpbmclMjByb29tc3xlbnwwfHwwfHx8MA%3D%3D" },
    ],
    price: 400,
    location: "Bangalore",
    country: "India",
    parentCategory: "professional",
    category: "meeting-rooms",
    pricingUnit: "hour",
    maxGuests: 8,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      capacity: 8,
      projector: true,
      whiteboard: true,
      videoConf: "4K camera",
      amenities: ["ac", "water", "smart board", "video conferencing"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 6,
      checkInTime: "08:00",
      checkOutTime: "21:00",
      advanceNotice: 6,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "flexible",
    },
  },

  // ===== PROFESSIONAL - Event Halls =====
  {
    title: "Grand Wedding Hall",
    description: "Elegant hall perfect for weddings, celebrations, and large gatherings.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1680807869624-07b389d623e8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1664391631217-d53431f0effd?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww" },
    ],
    price: 25000,
    location: "Chennai",
    country: "India",
    parentCategory: "professional",
    category: "event-halls",
    pricingUnit: "day",
    maxGuests: 300,
    geometry: { type: "Point", coordinates: [80.2707, 13.0827] },
    categoryFields: {
      capacity: 300,
      catering: "in-house available",
      parking: "100 cars",
      audioVisual: "full PA system, projector",
      eventTypes: ["wedding", "conference", "party", "exhibition"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 3,
      checkInTime: "08:00",
      checkOutTime: "23:00",
      advanceNotice: 168,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
  {
    title: "Modern Conference Center",
    description: "State-of-the-art conference facility with multiple breakout rooms and advanced technology.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1759477274116-e3cb02d2b9d8?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://plus.unsplash.com/premium_photo-1680807988328-7ba28ad24d9f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8ZXZlbnQlMjBoYWxsfGVufDB8fDB8fHww" },
    ],
    price: 18000,
    location: "Hyderabad",
    country: "India",
    parentCategory: "professional",
    category: "event-halls",
    pricingUnit: "day",
    maxGuests: 200,
    geometry: { type: "Point", coordinates: [78.4867, 17.385] },
    categoryFields: {
      capacity: 200,
      catering: "external allowed",
      parking: "80 cars",
      audioVisual: "stage lighting, sound system",
      eventTypes: ["conference", "seminar", "workshop"],
    },
    bookingSettings: {
      minStay: 1,
      maxStay: 2,
      checkInTime: "07:00",
      checkOutTime: "22:00",
      advanceNotice: 96,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },

  // ===== PROFESSIONAL - Studios =====
  {
    title: "Professional Photography Studio",
    description: "Fully equipped photography studio with cyclorama wall and professional lighting.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1664699106133-c338e54d395b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c3R1ZGlvc3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1661954400491-41d29414d354?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c3R1ZGlvfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1586232702178-f044c5f4d4b7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3R1ZGlvfGVufDB8fDB8fHww" },
    ],
    price: 800,
    location: "Delhi",
    country: "India",
    parentCategory: "professional",
    category: "studios",
    pricingUnit: "hour",
    maxGuests: 10,
    geometry: { type: "Point", coordinates: [77.1025, 28.7041] },
    categoryFields: {
      type: "photography",
      size: "1500 sq ft",
      equipment: ["lighting kit", "backdrops", "props"],
      soundproofed: false,
      lighting: "professional strobes included",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 12,
      checkInTime: "09:00",
      checkOutTime: "21:00",
      advanceNotice: 24,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Video Production Studio",
    description: "Professional video studio with green screen, lighting, and editing facilities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c3R1ZGlvfGVufDB8fDB8fHww",
    },
    gallery: [
      { filename: "gallery1", url: "https://plus.unsplash.com/premium_photo-1680955436007-264b858768e4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c3R1ZGlvfGVufDB8fDB8fHww" },
      { filename: "gallery2", url: "https://images.unsplash.com/photo-1603425013520-e0b30e6e37dc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3R1ZGlvfGVufDB8fDB8fHww" },
    ],
    price: 1200,
    location: "Mumbai",
    country: "India",
    parentCategory: "professional",
    category: "studios",
    pricingUnit: "hour",
    maxGuests: 15,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    categoryFields: {
      type: "video production",
      size: "2000 sq ft",
      equipment: ["4K cameras", "lighting", "green screen", "editing station"],
      soundproofed: true,
      lighting: "LED video lights",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 8,
      checkInTime: "08:00",
      checkOutTime: "22:00",
      advanceNotice: 48,
      instantBook: true,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "moderate",
    },
  },
  {
    title: "Music Recording Studio",
    description: "Professional recording studio with soundproof booths and mixing facilities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1636226570637-3fbda7ca09dc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHN0dWRpb3xlbnwwfHwwfHx8MA%3D%3D",
    },
    gallery: [],
    price: 1500,
    location: "Bangalore",
    country: "India",
    parentCategory: "professional",
    category: "studios",
    pricingUnit: "hour",
    maxGuests: 5,
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    categoryFields: {
      type: "music recording",
      size: "1200 sq ft",
      equipment: ["mixing console", "monitors", "microphones", "instruments"],
      soundproofed: true,
      lighting: "ambient",
    },
    bookingSettings: {
      minStay: 2,
      maxStay: 10,
      checkInTime: "10:00",
      checkOutTime: "22:00",
      advanceNotice: 72,
      instantBook: false,
    },
    policies: {
      petsAllowed: false,
      smokingAllowed: false,
      cancellationPolicy: "strict",
    },
  },
];

module.exports = { data: sampleListings };